#
# This file is part of Python Module for Cube Builder.
# Copyright (C) 2019-2021 INPE.
#
# Cube Builder free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

version: '3.1'

networks:
  cube_builder_net:

services:
  mq:
    image: rabbitmq:3-management
    container_name: cube-builder-rabbitmq
    hostname: cube-builder-rabbitmq
    restart: "always"
    volumes:
      - "./volumes/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - cube_builder_net

  cube-builder:
    container_name: cube-builder-api
    image: registry.dpi.inpe.br/brazil-data-cube/cube-builder:latest
    restart: "always"
    environment:
      - "RABBIT_MQ_URL=pyamqp://guest@cube-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc_collection_builder2019@bdc_collection_builder-pg:5432/bdc_scripts"
      - "DATA_DIR=/gfs"
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "FLASK_ENV=production"

    networks:
      - cube_builder_net
    ports:
      - "5000:5000"
    volumes:
      - /gfs:/gfs
    command: >
      bash -c "cube-builder run --host 0.0.0.0"
    depends_on:
      - mq

  worker:
    container_name: cube-builder-worker
    image: registry.dpi.inpe.br/brazildatacube/cube-builder:latest
    restart: "always"
    depends_on:
      - mq
      - cube-builder
    volumes:
      - /gfs:/gfs
    environment:
      - "RABBIT_MQ_URL=pyamqp://guest@cube-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:bdc_collection_builder2019@bdc_collection_builder-pg:5432/bdc_scripts"
      - "DATA_DIR=/gfs"
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "FLASK_ENV=production"
    command: >
      cube-builder worker -l INFO --concurrency 8 --max-tasks-per-child=16 -Q default,merge-cube,prepare-cube,blend-cube,publish-cube
    networks:
      - cube_builder_net
