#
# This file is part of Cube Builder.
# Copyright (C) 2022 INPE.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.
#

version: '3.1'

networks:
  cube_builder_net:

services:
  mq:
    image: rabbitmq:3-management
    container_name: cube-builder-rabbitmq
    hostname: cube-builder-rabbitmq
    restart: "always"
    volumes:
      - "./volumes/rabbitmq:/var/lib/rabbitmq"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - cube_builder_net

  postgres:
    container_name: cube-builder-pg
    image: postgis/postgis:13-3.1
    restart: "always"
    volumes:
      - "./volumes/pg:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_PASSWORD=postgres"
    ports:
      - "5432:5432"
    networks:
      - cube_builder_net

  cube-builder:
    build: .
    container_name: cube-builder-api
    image: registry.dpi.inpe.br/brazil-data-cube/cube-builder:latest
    restart: "always"
    environment:
      - "RABBIT_MQ_URL=pyamqp://guest@cube-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@cube-builder-pg:5432/bdc"
      - "DATA_DIR=/data"
      - "WORK_DIR=/workdir"
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "FLASK_ENV=production"
    networks:
      - cube_builder_net
    ports:
      - "5000:5000"
    volumes:
      - ./volumes/data:/data
      - ./volumes/workdir:/workdir
    command: >
      bash -c "cube-builder run --host 0.0.0.0"
    depends_on:
      - mq
      - postgres

  worker:
    build: .
    container_name: cube-builder-worker
    image: registry.dpi.inpe.br/brazil-data-cube/cube-builder:latest
    restart: "always"
    depends_on:
      - mq
      - cube-builder
    volumes:
      - ./volumes/data:/data
      - ./volumes/workdir:/workdir
    environment:
      - "RABBIT_MQ_URL=pyamqp://guest@cube-builder-rabbitmq"
      - "SQLALCHEMY_DATABASE_URI=postgresql://postgres:postgres@cube-builder-pg:5432/bdc"
      - "DATA_DIR=/data"
      - "WORK_DIR=/workdir"
      - "LC_ALL=C.UTF-8"
      - "LANG=C.UTF-8"
      - "FLASK_ENV=production"
    command: >
      cube-builder worker -l INFO --concurrency 8 --max-tasks-per-child=4 -Q default,merge-cube,prepare-cube,blend-cube,publish-cube
    networks:
      - cube_builder_net
