"""Add activities

Revision ID: 0c77843c0f5e
Revises:
Create Date: 2020-02-05 08:52:06.675752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c77843c0f5e'
down_revision = None
branch_labels = ('cube_builder',)
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('warped_collection_id', sa.String(length=64), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('scene_type', sa.String(), nullable=True),
    sa.Column('band', sa.String(length=64), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='cube_builder'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities', schema='cube_builder')
    # ### end Alembic commands ###
