"""add tile_id in activities

Revision ID: 4245348e2bac
Revises: 0c77843c0f5e
Create Date: 2020-03-09 21:01:15.324598

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4245348e2bac'
down_revision = '0c77843c0f5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('tile_id', sa.String(), nullable=False), schema='cube_builder')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'tile_id', schema='cube_builder')
    # ### end Alembic commands ###
