#
# This file is part of Python Module for Cube Builder.
# Copyright (C) 2019-2020 INPE.
#
# Cube Builder is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#

"""Add cube parameters.

Revision ID: b160749a148e
Revises: f639d83487b6
Create Date: 2021-03-05 17:15:24.716455

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b160749a148e'
down_revision = 'f639d83487b6'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cube_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['bdc.collections.id'], name=op.f('cube_parameters_collection_id_collections_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cube_parameters_pkey')),
    schema='cube_builder'
    )
    op.create_index(op.f('idx_cube_builder_cube_parameters_collection_id'), 'cube_parameters', ['collection_id'], unique=False, schema='cube_builder')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_cube_builder_cube_parameters_collection_id'), table_name='cube_parameters', schema='cube_builder')
    op.drop_table('cube_parameters', schema='cube_builder')
    # ### end Alembic commands ###
