#
# This file is part of Cube Builder.
# Copyright (C) 2022 INPE.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/gpl-3.0.html>.
#

"""Add cube parameters.

Revision ID: b160749a148e
Revises: f639d83487b6
Create Date: 2021-03-05 17:15:24.716455

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b160749a148e'
down_revision = 'f639d83487b6'
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cube_parameters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('metadata_', sa.JSON(), nullable=False),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['bdc.collections.id'], name=op.f('cube_parameters_collection_id_collections_fkey'), onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('cube_parameters_pkey')),
    schema='cube_builder'
    )
    op.create_index(op.f('idx_cube_builder_cube_parameters_collection_id'), 'cube_parameters', ['collection_id'], unique=False, schema='cube_builder')
    # ### end Alembic commands ###


def downgrade():
    """Downgrade this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_cube_builder_cube_parameters_collection_id'), table_name='cube_parameters', schema='cube_builder')
    op.drop_table('cube_parameters', schema='cube_builder')
    # ### end Alembic commands ###
