#
# This file is part of Python Module for Cube Builder.
# Copyright (C) 2019-2020 INPE.
#
# Cube Builder free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.
#
"""Define the alembic migrations for version 0.4.0."""

"""v0.4.0

Revision ID: f639d83487b6
Revises: 
Create Date: 2020-09-02 10:27:00.477876

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f639d83487b6'
down_revision = None
branch_labels = ('cube_builder',)
depends_on = None


def upgrade():
    """Upgrade this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.String(length=64), nullable=False),
    sa.Column('warped_collection_id', sa.String(length=64), nullable=False),
    sa.Column('activity_type', sa.String(length=64), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('tile_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('args', sa.JSON(), nullable=True),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('scene_type', sa.String(), nullable=True),
    sa.Column('band', sa.String(length=64), nullable=False),
    sa.Column('traceback', sa.Text(), nullable=True),
    sa.Column('created', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('activities_pkey')),
    schema='cube_builder'
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade this version migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities', schema='cube_builder')
    # ### end Alembic commands ###
